backend:
  name: github
  repo: JuanCarlosValort/datadriven-scm
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articulos"
    label: "Artículos y Temas"
    folder: "_temas"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
